// rclite browser loader -- generated by rclite.targets.wasm.BrowserWasm.
//
// A zero-WASI "reactor" module: it exports `rc_predict`, the linear `memory`,
// and `__heap_base`. The f32 build imports `env.tanhf` (supplied here as
// Math.tanh); the quantized integer build imports nothing at all.
//
// Template placeholders (filled in by BrowserWasm):
//   @@DTYPE@@        -- "f32" | "i8" | "i16" | "i32"
//   @@K@@ / @@M@@    -- input / output units
//   @@ARRAY@@        -- TypedArray ctor for the wasm storage (Float32Array/Int…)
//   @@BYTES@@        -- bytes per element
//   @@HAS_TANHF@@    -- "true" | "false"
//   @@INPUT_SCALE@@  -- quantized input scale (1 for f32)
//   @@STATE_SCALE@@  -- quantized output (state) scale (1 for f32)
//   @@IN_OFFSET@@ / @@IN_SCALING@@ -- model input preprocessing (for the quant API)

const K = @@K@@;
const M = @@M@@;
const BYTES = @@BYTES@@;
const Storage = @@ARRAY@@;
const QUANTIZED = "@@DTYPE@@" !== "f32";
const INPUT_SCALE = @@INPUT_SCALE@@;
const STATE_SCALE = @@STATE_SCALE@@;
const IN_OFFSET = @@IN_OFFSET@@;
const IN_SCALING = @@IN_SCALING@@;

const align16 = (n) => (n + 15) & ~15;

/**
 * Load and instantiate an rclite reactor module.
 * @param {string|URL|Response|ArrayBuffer} src - URL/Response/bytes of the .wasm
 * @returns {Promise<{predict, predictRaw, memory, exports, info}>}
 */
export async function loadRclite(src) {
  const imports = {};
  if (@@HAS_TANHF@@) {
    // The f32 kernel calls libm `tanhf`; browsers have no WASI, so wire it
    // to the JS Math.tanh (f32-rounded for closer parity with wasi-libc).
    imports.env = { tanhf: (x) => Math.fround(Math.tanh(x)) };
  }

  let instance;
  if (typeof Response !== "undefined" && src instanceof Response) {
    ({ instance } = await WebAssembly.instantiateStreaming(src, imports));
  } else if (typeof src === "string" || src instanceof URL) {
    const resp = await fetch(src);
    ({ instance } = await WebAssembly.instantiateStreaming(resp, imports));
  } else {
    ({ instance } = await WebAssembly.instantiate(src, imports));
  }

  const { memory, rc_predict, __heap_base } = instance.exports;
  const heapBase = __heap_base ? __heap_base.value : 1024;

  function ensureCapacity(bytesNeeded) {
    const have = memory.buffer.byteLength;
    if (heapBase + bytesNeeded > have) {
      const grow = Math.ceil((heapBase + bytesNeeded - have) / 65536);
      memory.grow(grow);
    }
  }

  // Run the kernel on storage-domain values: `input` is a flat (T*K) array of
  // integers (quantized build) or floats (f32 build). Returns the raw (T*M)
  // storage-domain output.
  function predictRaw(input) {
    const T = Math.floor(input.length / K);
    const inBytes = align16(T * K * BYTES);
    const outBytes = align16(T * M * BYTES);
    ensureCapacity(inBytes + outBytes);
    const xPtr = heapBase;
    const yPtr = heapBase + inBytes;
    // Re-create views every call: memory.grow() can detach the old buffer.
    new Storage(memory.buffer, xPtr, T * K).set(input);
    new Storage(memory.buffer, yPtr, T * M).fill(0);
    rc_predict(BigInt(T), xPtr, yPtr);
    return new Storage(memory.buffer, yPtr, T * M).slice();
  }

  // Float convenience API. For the quantized build this quantizes the input
  // (round(x * input_scale), saturated) and dequantizes the output
  // (y / state_scale). NOTE: this mirrors rclite's fixed-point quantizer for
  // the common case; for guaranteed bit-exact parity, quantize with the
  // Python tooling and call predictRaw().
  function predict(inputFloat) {
    if (!QUANTIZED) {
      const out = predictRaw(Float32Array.from(inputFloat));
      return out;
    }
    const lim = (1 << (BYTES * 8 - 1)) - 1;
    const q = new Storage(inputFloat.length);
    for (let i = 0; i < inputFloat.length; i++) {
      let v = Math.round(inputFloat[i] * INPUT_SCALE);
      if (v > lim) v = lim; else if (v < -lim - 1) v = -lim - 1;
      q[i] = v;
    }
    const raw = predictRaw(q);
    const out = new Float32Array(raw.length);
    for (let i = 0; i < raw.length; i++) out[i] = raw[i] / STATE_SCALE;
    return out;
  }

  return {
    predict,
    predictRaw,
    memory,
    exports: instance.exports,
    info: { dtype: "@@DTYPE@@", K, M, quantized: QUANTIZED,
            inputScale: INPUT_SCALE, stateScale: STATE_SCALE },
  };
}

export default loadRclite;
