/* NES front-end for the rclite Echo State Network demo.
 *
 * Like the GBA demo, it runs the affine-quantized reservoir kernel (rc_kernel.c,
 * emitted by rclite) on the embedded Mackey-Glass eval inputs and plots the
 * ground truth (green) against the ESN's one-step prediction (red), with the
 * text labels MACKEY GLASS / TRUTH / PRED.
 *
 * Rendering uses CHR-RAM as a bitmap. The background addresses 256 distinct 8x8
 * tiles: tiles 0..223 hold a 256x56 plot band (drawn pixel-by-pixel into a
 * framebuffer in PRG-RAM at $6000, then streamed to CHR-RAM with rendering
 * off), and tiles 224+ hold the label glyphs. The labels are drawn first and
 * rendering is enabled immediately, so the screen is never blank while the
 * 6502 grinds through the integer kernel; the plot appears when it finishes.
 *
 * One background palette [black, green, red, white] colours everything: a curve
 * pixel sets plane 0 (green = truth) or plane 1 (red = pred), overlap -> white;
 * a label glyph is baked into plane 0, plane 1 or both to pick its colour.
 *
 * esn_data.h (generated by build.py) provides the eval inputs, the quantized
 * truth, and the quant->row mapping endpoints. font.h provides a 5x7 glyph set
 * indexed by ASCII code. NB: `int` is 16-bit on the 6502.
 */
#include <nes.h>
#include <neslib.h>
#include <ines.h>
#include <stdint.h>
#include "esn_data.h"
#include "font.h"

MAPPER_CHR_RAM_KB(8);
MAPPER_CHR_ROM_KB(0);
MAPPER_PRG_RAM_KB(8);

#define PLOT_W 256
#define PLOT_H 56
#define PLOT_COLS 32
#define PLOT_ROWS 7
#define PLOT_TILES (PLOT_COLS * PLOT_ROWS)   /* 224, indices 0..223 */
#define BLANK_TILE 255
#define PLOT_NT_ROW 14

#define COL_GREEN 1   /* plane 0 -> palette colour 1 */
#define COL_RED   2   /* plane 1 -> palette colour 2 */
#define COL_WHITE 3   /* both planes -> palette colour 3 */

/* palette: black, green (truth), red (pred), white (overlap / title) */
static const uint8_t palette[16] = {
    0x0f, 0x1a, 0x16, 0x30,  0x0f, 0, 0, 0,
    0x0f, 0,    0,    0,      0x0f, 0, 0, 0,
};

extern void rc_predict(int32_t T, const int16_t *X, int16_t *Y);
static int16_t pred_q[EVAL_STEPS];

/* tile framebuffer for the plot band, in PRG-RAM ($6000) */
static uint8_t *const FB = (uint8_t *)0x6000;
#define FB_BYTES (PLOT_TILES * 16)

static uint8_t g_next_tile = PLOT_TILES;   /* label glyphs allocate from here */

/* Assign the pixel to exactly `color` (overwrite, not OR), so a later curve
 * draws *on top* of an earlier one — matching the GBA demo's framebuffer: the
 * red prediction overwrites the green truth where they overlap (no white). */
static void fb_plot(int x, int y, uint8_t color)
{
    unsigned tile, idx;
    uint8_t row, bit, keep;
    if (x < 0 || x >= PLOT_W || y < 0 || y >= PLOT_H)
        return;
    tile = ((unsigned)(y >> 3)) * PLOT_COLS + (unsigned)(x >> 3);
    row = (uint8_t)(y & 7);
    bit = (uint8_t)(0x80u >> (x & 7));
    idx = tile * 16u + row;
    keep = (uint8_t)~bit;
    FB[idx]     = (uint8_t)((FB[idx]     & keep) | ((color & 1) ? bit : 0));
    FB[idx + 8] = (uint8_t)((FB[idx + 8] & keep) | ((color & 2) ? bit : 0));
}

static void fb_seg(int x0, int y0, int x1, int y1, uint8_t color)
{
    int xx, dx = x1 - x0;
    if (dx <= 0) { fb_plot(x1, y1, color); return; }
    for (xx = x0; xx <= x1; xx++)
        fb_plot(xx, y0 + (int)((long)(y1 - y0) * (xx - x0) / dx), color);
}

/* map an output-scale quant value to a plot row (row 0 = top = Y_Q_HI).
 * `int` is 16-bit and the quant span exceeds 32767, so compute in `long`. */
static int q_to_row(int q)
{
    long span = (long)Y_Q_HI - (long)Y_Q_LO;
    long off  = ((long)q - (long)Y_Q_LO) * (long)(PLOT_H - 1);
    int row = (PLOT_H - 1) - (int)(off / span);
    if (row < 0) row = 0;
    if (row >= PLOT_H) row = PLOT_H - 1;
    return row;
}

static void draw_curve(const int16_t *q, uint8_t color)
{
    int i, x, y, xp = 0, yp = 0;
    for (i = 0; i < EVAL_STEPS; i++) {
        x = (int)((long)i * (PLOT_W - 1) / (EVAL_STEPS - 1));
        y = q_to_row((int)q[i]);
        if (i > 0) fb_seg(xp, yp, x, y, color);
        else       fb_plot(x, y, color);
        xp = x; yp = y;
    }
}

/* draw a text label, baking `color` into the glyph planes; allocates one
 * CHR tile per non-space character (rendering must be off). */
static void put_label(uint8_t col, uint8_t row, const char *s, uint8_t color)
{
    uint8_t buf[16], k, t, i = 0;
    const uint8_t *gl;
    char c;
    while ((c = s[i]) != 0) {
        if (c == ' ') {
            vram_adr(0x2000 + (unsigned)row * 32 + col + i);
            vram_put(BLANK_TILE);
        } else {
            t = g_next_tile++;
            gl = &FONT[((unsigned)(uint8_t)(c - FONT_FIRST)) * 16];
            for (k = 0; k < 8; k++) {
                buf[k]     = (color & 1) ? gl[k] : 0;
                buf[k + 8] = (color & 2) ? gl[k] : 0;
            }
            vram_adr((unsigned)t * 16);
            vram_write(buf, 16);
            vram_adr(0x2000 + (unsigned)row * 32 + col + i);
            vram_put(t);
        }
        i++;
    }
}

int main(void)
{
    unsigned i;
    uint8_t r, c;

    /* 1. labels + empty plot area, rendering ON immediately */
    ppu_off();
    pal_bg(palette);
    vram_adr(0x0000);
    vram_fill(0, 0x1000);                 /* clear pattern table 0 */
    vram_adr(0x2000);
    vram_fill(BLANK_TILE, 0x3C0);         /* blank nametable */
    vram_adr(0x23C0);
    vram_fill(0, 64);                     /* attributes -> palette 0 */
    put_label(2, 2,  "MACKEY GLASS", COL_WHITE);
    put_label(2, 4,  "TRUTH", COL_GREEN);
    put_label(2, 5,  "PRED", COL_RED);
    scroll(0, 0);
    ppu_on_bg();

    /* 2. compute the prediction on-device */
    rc_predict((int32_t)EVAL_STEPS, EVAL_X_Q, pred_q);

    /* 3. rasterise truth (green) then prediction (red) into the framebuffer */
    for (i = 0; i < FB_BYTES; i++) FB[i] = 0;
    draw_curve(TRUTH_Q, COL_GREEN);
    draw_curve(pred_q, COL_RED);

    /* 4. blit the plot band to the PPU with rendering off */
    ppu_off();
    vram_adr(0x0000);
    vram_write(FB, FB_BYTES);             /* plot tiles 0..223 */
    for (r = 0; r < PLOT_ROWS; r++) {
        vram_adr(0x2000 + (PLOT_NT_ROW + r) * 32);
        for (c = 0; c < PLOT_COLS; c++)
            vram_put((uint8_t)(r * PLOT_COLS + c));
    }
    ppu_on_bg();

    *(volatile uint8_t *)0x7000 = 0xA5;   /* signal the screenshot driver */
    for (;;) ppu_wait_nmi();
    return 0;
}
