"""Portable-C emitter for the affine quantized reservoir kernel.

Produces a single self-contained `.c` source that implements `rc_predict`
with the exact integer arithmetic of `AffineQuantizedExecutor` /
`_AffineLowerer`, so the C kernel is bit-exact with the Python reference
and the host JIT.

Design goals:
  * **Portable.** Compiles with any C99 compiler. On AVR (`__AVR__`) the
    weight/LUT tables live in Flash via `PROGMEM` and are read with
    `pgm_read_*`; on the host they are plain arrays, so the same source
    can be compiled with host gcc and checked bit-for-bit.
  * **Small SRAM.** Only the reservoir state and pre buffers (and a tiny
    u_pre scratch) live in RAM — `2*N + K` bytes for an i8 model. Weights
    stay in Flash. A structured-topology (SCR/DLR/DLRB) i8 model fits an
    Arduino Uno (2 KB SRAM) comfortably.

Supported (mirrors the LLVM affine path):
  * storage i8 / i16, mixed-precision i16 W_out
  * topologies: SCR / DLR / DLRB (scalar chain) and dense (W_res matmul)
  * LUT strategies: direct / linear_interp / polynomial
  * integer input preprocess (input_offset / input_scaling != 0/1)
  * include_bias / include_input readout blocks
"""
from __future__ import annotations
from typing import List

import numpy as np

from rclite.core.profile import Topology
from rclite.quant.affine.quantize import AffineQuantizedModel
from rclite.quant.affine.lut import LUTKind


_C_TYPE = {8: "int8_t", 16: "int16_t", 32: "int32_t"}
_RD = {8: "RC_RD8", 16: "RC_RD16", 32: "RC_RD32"}


def _arr(name: str, ctype: str, values, rd_macro: str) -> str:
    """Emit a PROGMEM const array declaration."""
    body = ", ".join(str(int(v)) for v in np.asarray(values).reshape(-1))
    return f"static const {ctype} {name}[] RC_PROGMEM = {{ {body} }};"


def emit_affine_kernel_c(qmodel: AffineQuantizedModel,
                          fn_name: str = "rc_predict",
                          *, allow_i32_accum: bool = False,
                          head: str = None, sparse=None) -> str:
    """Emit the affine kernel as portable C.

    `allow_i32_accum` enables i32 (instead of i64) matmul accumulators
    wherever the worst-case magnitude provably fits — cheaper MACs
    (__mulhisi3 vs __muldi3) on 8-bit targets. It is **off by default**
    because avr-gcc 7.x miscompiles the i32 widening-MAC loop into a hang
    (the code is bit-exact on modern host gcc / newer avr-gcc, so the
    Arduino target keeps it off and the host parity tests exercise it on).
    The requantize always uses the union high-word trick, which is safe
    everywhere and removes the libgcc __ashrdi3 64-bit-shift loop.

    `sparse` (None / "csr" / "auto" / "unroll") specializes the dense W_res
    matvec to its nonzeros for RANDOM/ESN_STANDARD topologies. The C path
    emits a **CSR** kernel (bounded code size — the right choice for the
    2KB-SRAM/Flash targets that use this template); "unroll"/"auto" resolve
    to CSR here. Bit-exact with the dense kernel (skips exact-zero MACs in
    ascending column order; the affine row-sum correction is unchanged).
    """
    rc = qmodel.rc
    cfg = qmodel.config
    sb = qmodel.storage_bits
    wob = qmodel.w_out_storage_bits
    storage_t = _C_TYPE[sb]
    wout_t = _C_TYPE[wob]
    rd_s = _RD[sb]
    rd_w = _RD[wob]

    N, K, M, F = qmodel.N, qmodel.K, qmodel.M, qmodel.F
    qmin = -(1 << (sb - 1))
    qmax = (1 << (sb - 1)) - 1

    is_structured = rc.reservoir.topology in (
        Topology.DLR, Topology.DLRB, Topology.SCR)
    topo = rc.reservoir.topology.name

    # Sparse W_res (CSR) for dense topologies. Code size stays bounded, so
    # any requested strategy maps to CSR on this code-size-constrained path.
    use_sparse = bool(sparse) and not is_structured
    if use_sparse:
        from rclite.ir.passes.sparsify import build_csr
        _wres_val, _wres_col, _wres_rowptr = build_csr(qmodel.W_res_q)
        col_t = "int16_t" if N <= 32767 else "int32_t"
        rd_col = "RC_RD16" if N <= 32767 else "RC_RD32"

    # Per-channel reservoir-step multiplier (per-row M0/n) for dense topologies.
    use_per_channel_res = (qmodel.M_res_M0_arr is not None) and not is_structured
    # Per-channel readout multiplier (per output-row M0/n).
    use_per_channel_out = qmodel.M_out_state_M0_arr is not None

    # Chain constants (match ir_builder)
    wqmin, wqmax = -(1 << (wob - 1)), (1 << (wob - 1)) - 1

    def _qw(v):
        return max(wqmin, min(wqmax, int(round(v / cfg.W_out_state.scale))))

    # chain weights are quantized at the W_res (i8) scale, not W_out
    rqmin, rqmax = -(1 << (sb - 1)), (1 << (sb - 1)) - 1

    def _qchain(v):
        return max(rqmin, min(rqmax, int(round(v / cfg.W_res.scale))))

    chain_weight_q = _qchain(float(rc.reservoir.chain_weight))
    chain_feedback_q = _qchain(float(rc.reservoir.chain_feedback))

    art = qmodel.lut_artifacts
    strat = qmodel.lut_strategy

    L: List[str] = []
    a = L.append

    # ---- header ----
    a("/* Auto-generated by rclite — affine quantized reservoir kernel. */")
    a("/* Portable C99. On AVR, tables live in Flash (PROGMEM). */")
    a("#include <stdint.h>")
    a("#ifdef __AVR__")
    a("#include <avr/pgmspace.h>")
    a("#define RC_PROGMEM PROGMEM")
    a("#define RC_RD8(p)  ((int8_t)pgm_read_byte(p))")
    a("#define RC_RD16(p) ((int16_t)pgm_read_word(p))")
    a("#define RC_RD32(p) ((int32_t)pgm_read_dword(p))")
    a("#else")
    a("#define RC_PROGMEM")
    a("#define RC_RD8(p)  (*(p))")
    a("#define RC_RD16(p) (*(p))")
    a("#define RC_RD32(p) (*(p))")
    a("#endif")
    a("")
    a(f"#define RC_N {N}")
    a(f"#define RC_K {K}")
    a(f"#define RC_M {M}")
    a(f"#define RC_F {F}")
    a(f"#define RC_QMIN ({qmin})")
    a(f"#define RC_QMAX ({qmax})")
    a("typedef %s rc_storage_t;" % storage_t)
    a("")

    # ---- weight / LUT tables ----
    a(_arr("rc_W_in", storage_t, qmodel.W_in_q, rd_s))
    a(_arr("rc_W_out", wout_t, qmodel.W_out_q, rd_w))
    a(_arr("rc_row_sum_W_in", "int32_t", qmodel.row_sum_W_in, "RC_RD32"))
    a(_arr("rc_row_sum_Wout_state", "int32_t",
            qmodel.row_sum_Wout_state, "RC_RD32"))
    if rc.readout.include_input:
        a(_arr("rc_row_sum_Wout_input", "int32_t",
                qmodel.row_sum_Wout_input, "RC_RD32"))
    if use_per_channel_out:
        a(_arr("rc_M_out_state_M0", "int32_t", qmodel.M_out_state_M0_arr, "RC_RD32"))
        a(_arr("rc_M_out_state_n", "int32_t", qmodel.M_out_state_n_arr, "RC_RD32"))
        if rc.readout.include_bias:
            a(_arr("rc_M_out_bias_M0", "int32_t", qmodel.M_out_bias_M0_arr, "RC_RD32"))
            a(_arr("rc_M_out_bias_n", "int32_t", qmodel.M_out_bias_n_arr, "RC_RD32"))
        if rc.readout.include_input:
            a(_arr("rc_M_out_input_M0", "int32_t", qmodel.M_out_input_M0_arr, "RC_RD32"))
            a(_arr("rc_M_out_input_n", "int32_t", qmodel.M_out_input_n_arr, "RC_RD32"))
    if not is_structured:
        if use_sparse:
            a(_arr("rc_W_res_val", storage_t, _wres_val, rd_s))
            a(_arr("rc_W_res_col", col_t, _wres_col, rd_col))
            a(_arr("rc_W_res_rowptr", "int32_t", _wres_rowptr, "RC_RD32"))
        else:
            a(_arr("rc_W_res", storage_t, qmodel.W_res_q, rd_s))
        a(_arr("rc_row_sum_W_res", "int32_t", qmodel.row_sum_W_res, "RC_RD32"))
        if use_per_channel_res:
            a(_arr("rc_M_res_M0", "int32_t", qmodel.M_res_M0_arr, "RC_RD32"))
            a(_arr("rc_M_res_n", "int32_t", qmodel.M_res_n_arr, "RC_RD32"))
    if strat.kind in (LUTKind.DIRECT, LUTKind.LINEAR_INTERP):
        a(_arr("rc_lut", storage_t, qmodel.lut_q, rd_s))
    if head == "proba":
        import numpy as _np
        from rclite.quant.softmax_lut import (
            SoftmaxLUTSpec, build_params as _build_sm,
        )
        _sm = _build_sm(SoftmaxLUTSpec(), cfg.output.scale, sb,
                        _np.dtype(f"int{sb}"))
        a(_arr("rc_sm_lut", storage_t, _sm.lut_q, rd_s))
        a(f"#define RC_SM_N {_sm.n}")
        a(f"#define RC_SM_DMIN ({_sm.dmin_q})")
        a(f"#define RC_SM_IDXF {_sm.idx_frac}")
        a(f"#define RC_SM_PF {_sm.prob_frac}")
    a("")

    # ---- SRAM state buffers ----
    a("static rc_storage_t rc_h[RC_N];")
    a("static rc_storage_t rc_pre[RC_N];")
    if qmodel.has_integer_preprocess:
        a("static rc_storage_t rc_u[RC_K];")
    a("")

    # ---- helpers ----
    # Requantize = round(x * M0 / 2^n). Two AVR-specific tricks:
    #   * int32 operands keep gcc's widening-multiply detection
    #     (32x32->64 = __mulsidi3, ~13 instr) instead of a full __muldi3.
    #   * The final 64-bit `>> n` is done by hand: avr-gcc (7.x) routes ALL
    #     64-bit shifts — even constant ones — to the libgcc __ashrdi3 loop,
    #     so instead we grab the high 32-bit word through a union (free
    #     register access on little-endian AVR/x86) and finish with a single
    #     32-bit shift, which gcc *does* inline. always_inline + the constant
    #     n at each call site fold the rounding add and the branch away.
    a("typedef union { int64_t q; struct { uint32_t lo; int32_t hi; } w; } rc_i64u;")
    a("static inline __attribute__((always_inline)) "
      "int32_t rc_rq_(int32_t x, int32_t M0, uint8_t n){")
    a("    rc_i64u u;")
    a("    u.q = (int64_t)x * (int64_t)M0 + ((int64_t)1 << (n - 1));")
    a("    if (n >= 32) return u.w.hi >> (n - 32);")
    a("    return (int32_t)((u.w.lo >> n) | ((uint32_t)u.w.hi << (32 - n)));")
    a("}")
    a("#define RC_RQ(x, M0, N) rc_rq_((x), (M0), (N))")
    a("static int32_t rc_clamp32(int64_t v){")
    a("    if (v < (int64_t)(-2147483647-1)) return (-2147483647-1);")
    a("    if (v > (int64_t)2147483647) return 2147483647;")
    a("    return (int32_t)v;")
    a("}")
    a("static rc_storage_t rc_sat(int32_t v){")
    a("    if (v < RC_QMIN) v = RC_QMIN;")
    a("    if (v > RC_QMAX) v = RC_QMAX;")
    a("    return (rc_storage_t)v;")
    a("}")
    a("")

    # ---- activation ----
    a("static rc_storage_t rc_activate(int32_t pre){")
    if strat.kind == LUTKind.DIRECT:
        a(f"    int32_t idx = pre + {qmodel.lut_offset};")
        a(f"    return ({storage_t}){rd_s}(&rc_lut[idx]);")
    elif strat.kind == LUTKind.LINEAR_INTERP:
        f = strat.interp_frac_bits
        n = strat.n_entries
        a(f"    int32_t norm = pre + {qmodel.lut_offset};")
        a(f"    int32_t tq = RC_RQ(norm, {art.idx_M0}, {art.idx_n});")
        a(f"    int32_t idx = tq >> {f};")
        a(f"    if (idx < 0) idx = 0; if (idx > {n - 2}) idx = {n - 2};")
        a(f"    int32_t frac = tq - (idx << {f});")
        a(f"    int32_t y0 = {rd_s}(&rc_lut[idx]);")
        a(f"    int32_t y1 = {rd_s}(&rc_lut[idx + 1]);")
        a(f"    int32_t v = y0 + (((y1 - y0) * frac) >> {f});")
        a("    return rc_sat(v);")
    elif strat.kind == LUTKind.POLYNOMIAL:
        qf = strat.poly_qf_bits
        a(f"    int32_t cx = pre - {cfg.pre.zero_point};")
        a(f"    int64_t x = (int64_t)RC_RQ(cx, {art.x_to_qf_M0}, {art.x_to_qf_n});")
        a(f"    if (x < {-art.x_clip_qf}) x = {-art.x_clip_qf};")
        a(f"    if (x > {art.x_clip_qf}) x = {art.x_clip_qf};")
        a(f"    int64_t x2 = (x * x) >> {qf};")
        a(f"    int64_t inner = ((x2 * {art.poly_a5_qf}) >> {qf}) + {art.poly_a3_qf};")
        a(f"    int64_t outer = ((x2 * inner) >> {qf}) + {art.poly_a1_qf};")
        a(f"    int64_t y = (x * outer) >> {qf};")
        a(f"    if (y < {-art.one_qf}) y = {-art.one_qf};")
        a(f"    if (y > {art.one_qf}) y = {art.one_qf};")
        a(f"    int32_t d = RC_RQ((int32_t)y, {art.qf_to_state_M0}, {art.qf_to_state_n});")
        a(f"    return rc_sat(d + {cfg.state.zero_point});")
    a("}")
    a("")

    # ---- kernel ----
    zp_upre = cfg.u_pre.zero_point
    zp_state = cfg.state.zero_point
    zp_pre = cfg.pre.zero_point
    zp_input = cfg.input.zero_point
    zp_output = cfg.output.zero_point

    if head not in (None, "logits", "classify", "proba"):
        raise NotImplementedError(
            f"affine C kernel supports head in (None, 'logits', 'classify', "
            f"'proba'); got {head!r}"
        )
    classify = head == "classify"
    proba = head == "proba"
    y_type = "int32_t" if classify else "rc_storage_t"
    a(f"void {fn_name}(int32_t T, const rc_storage_t *X, {y_type} *Y){{")
    a("    int32_t t, i, j, k, m;")
    if classify:
        a("    int32_t best_m; int32_t best_v;")
    if proba:
        a("    int32_t sm_max; int64_t sm_sum;")
        a("    rc_storage_t rc_lg[RC_M];")
        a("    int32_t rc_eq[RC_M];")
    a(f"    for (i = 0; i < RC_N; i++) rc_h[i] = {zp_state};")
    a("    for (t = 0; t < T; t++) {")

    # preprocess
    if qmodel.has_integer_preprocess:
        a("        for (k = 0; k < RC_K; k++) {")
        a(f"            int32_t cx = (int32_t)X[t*RC_K + k] - {zp_input};")
        a(f"            int32_t up = RC_RQ(cx, {qmodel.pre_M0}, {qmodel.pre_n}) + {qmodel.pre_const};")
        a("            rc_u[k] = rc_sat(up);")
        a("        }")
        u_expr = "rc_u[k]"
    else:
        u_expr = "X[t*RC_K + k]"

    # Accumulator widths: i32 where products+sums provably fit (i8 models,
    # bounded N) → cheap MACs (__mulhisi3/__mulsi3) instead of i64 __muldi3;
    # i64 only when an accumulator could overflow (i16 reservoirs). Values are
    # identical to the i64 path within the safe range, so parity is preserved.
    if allow_i32_accum:
        res_bits, ro_bits = _accum_bits(qmodel, is_structured,
                                         chain_weight_q, chain_feedback_q)
    else:
        res_bits, ro_bits = 64, 64   # safe everywhere (avr-gcc 7.x)
    res_t = "int32_t" if res_bits == 32 else "int64_t"
    ro_t = "int32_t" if ro_bits == 32 else "int64_t"
    res_cast = "(int32_t)" if res_bits == 32 else "(int64_t)"
    ro_cast = "(int32_t)" if ro_bits == 32 else "(int64_t)"

    def _clamp(expr, bits):
        return expr if bits == 32 else f"rc_clamp32({expr})"

    # reservoir pre-activation
    a("        for (i = 0; i < RC_N; i++) {")
    a("            int32_t acc_in = 0;")
    a("            for (k = 0; k < RC_K; k++)")
    a(f"                acc_in += (int32_t){rd_s}(&rc_W_in[i*RC_K + k]) * (int32_t)({u_expr});")
    a(f"            acc_in -= {zp_upre} * RC_RD32(&rc_row_sum_W_in[i]);")
    a(f"            int32_t rq_in = RC_RQ(acc_in, {qmodel.M_in_M0}, {qmodel.M_in_n});")
    # W_res contribution
    if is_structured:
        _emit_chain_c(a, topo, N, chain_weight_q, chain_feedback_q,
                       zp_state, rd_s, res_t, res_cast)
    elif use_sparse:
        a(f"            {res_t} acc_res = 0;")
        a("            { int32_t rp = RC_RD32(&rc_W_res_rowptr[i]);")
        a("              int32_t rpe = RC_RD32(&rc_W_res_rowptr[i+1]);")
        a("              for (j = rp; j < rpe; j++)")
        a(f"                acc_res += {res_cast}{rd_s}(&rc_W_res_val[j]) * "
          f"{res_cast}rc_h[{rd_col}(&rc_W_res_col[j])]; }}")
        a(f"            acc_res -= {res_cast}{zp_state} * {res_cast}RC_RD32(&rc_row_sum_W_res[i]);")
    else:
        a(f"            {res_t} acc_res = 0;")
        a("            for (j = 0; j < RC_N; j++)")
        a(f"                acc_res += {res_cast}{rd_s}(&rc_W_res[i*RC_N + j]) * {res_cast}rc_h[j];")
        a(f"            acc_res -= {res_cast}{zp_state} * {res_cast}RC_RD32(&rc_row_sum_W_res[i]);")
    if use_per_channel_res:
        # per-row (M0[i], n[i]) — reuse the same runtime requantize fn.
        a(f"            int32_t rq_res = RC_RQ({_clamp('acc_res', res_bits)}, "
          f"RC_RD32(&rc_M_res_M0[i]), RC_RD32(&rc_M_res_n[i]));")
    else:
        a(f"            int32_t rq_res = RC_RQ({_clamp('acc_res', res_bits)}, "
          f"{qmodel.M_res_M0}, {qmodel.M_res_n});")
    a(f"            rc_pre[i] = rc_sat({zp_pre + qmodel.bias_pre} + rq_in + rq_res);")
    a("        }")

    # activation + leaky integration
    a("        for (i = 0; i < RC_N; i++) {")
    a("            int32_t act = rc_activate((int32_t)rc_pre[i]);")
    a(f"            int32_t hc = (int32_t)rc_h[i] - {zp_state};")
    a(f"            int32_t ac = act - {zp_state};")
    a(f"            int32_t d = RC_RQ(ac - hc, {qmodel.leak_M0}, {qmodel.leak_n});")
    a(f"            rc_h[i] = rc_sat({zp_state} + hc + d);")
    a("        }")

    # readout
    off_bias = 0
    off_input = 1 if rc.readout.include_bias else 0
    off_state = off_input + (K if rc.readout.include_input else 0)
    if classify:
        a("        best_m = 0; best_v = 0;")
    a("        for (m = 0; m < RC_M; m++) {")
    a(f"            int32_t y = {zp_output};")
    if rc.readout.include_bias:
        m_bias = ("RC_RD32(&rc_M_out_bias_M0[m]), RC_RD32(&rc_M_out_bias_n[m])"
                  if use_per_channel_out
                  else f"{qmodel.M_out_bias_M0}, {qmodel.M_out_bias_n}")
        a(f"            y += RC_RQ((int32_t){rd_w}(&rc_W_out[m*RC_F + {off_bias}]), "
          f"{m_bias});")
    if rc.readout.include_input:
        a(f"            {ro_t} acc_i = 0;")
        a("            for (k = 0; k < RC_K; k++)")
        a(f"                acc_i += {ro_cast}{rd_w}(&rc_W_out[m*RC_F + {off_input} + k]) "
          f"* {ro_cast}X[t*RC_K + k];")
        a(f"            acc_i -= {ro_cast}{zp_input} * {ro_cast}RC_RD32(&rc_row_sum_Wout_input[m]);")
        m_in = ("RC_RD32(&rc_M_out_input_M0[m]), RC_RD32(&rc_M_out_input_n[m])"
                if use_per_channel_out
                else f"{qmodel.M_out_input_M0}, {qmodel.M_out_input_n}")
        a(f"            y += RC_RQ({_clamp('acc_i', ro_bits)}, {m_in});")
    a(f"            {ro_t} acc_s = 0;")
    a("            for (j = 0; j < RC_N; j++)")
    a(f"                acc_s += {ro_cast}{rd_w}(&rc_W_out[m*RC_F + {off_state} + j]) "
      f"* {ro_cast}rc_h[j];")
    a(f"            acc_s -= {ro_cast}{zp_state} * {ro_cast}RC_RD32(&rc_row_sum_Wout_state[m]);")
    m_st = ("RC_RD32(&rc_M_out_state_M0[m]), RC_RD32(&rc_M_out_state_n[m])"
            if use_per_channel_out
            else f"{qmodel.M_out_state_M0}, {qmodel.M_out_state_n}")
    a(f"            y += RC_RQ({_clamp('acc_s', ro_bits)}, {m_st});")
    if classify:
        # argmax over the saturated quantized scores (monotone in the logits).
        a("            int32_t yq = (int32_t)rc_sat(y);")
        a("            if (m == 0 || yq > best_v) { best_v = yq; best_m = m; }")
    elif proba:
        a("            rc_lg[m] = rc_sat(y);")
    else:
        a("            Y[t*RC_M + m] = rc_sat(y);")
    a("        }")
    if classify:
        a("        Y[t] = best_m;")
    elif proba:
        a("        sm_max = rc_lg[0];")
        a("        for (m = 1; m < RC_M; m++) if (rc_lg[m] > sm_max) sm_max = rc_lg[m];")
        a("        sm_sum = 0;")
        a("        for (m = 0; m < RC_M; m++) {")
        a("            int32_t d = (int32_t)rc_lg[m] - sm_max;")
        a("            if (d < RC_SM_DMIN) d = RC_SM_DMIN;")
        a("            int64_t pos = ((int64_t)(d - (RC_SM_DMIN)) * (RC_SM_N - 1) << RC_SM_IDXF) / (-(RC_SM_DMIN));")
        a("            int32_t i0 = (int32_t)(pos >> RC_SM_IDXF);")
        a("            if (i0 < 0) i0 = 0; if (i0 > RC_SM_N - 2) i0 = RC_SM_N - 2;")
        a("            int64_t frac = pos - ((int64_t)i0 << RC_SM_IDXF);")
        a(f"            int32_t y0 = {rd_s}(&rc_sm_lut[i0]); int32_t y1 = {rd_s}(&rc_sm_lut[i0 + 1]);")
        a("            int64_t ev = (int64_t)y0 + (((int64_t)(y1 - y0) * frac) >> RC_SM_IDXF);")
        a("            rc_eq[m] = (int32_t)ev; sm_sum += ev;")
        a("        }")
        a("        for (m = 0; m < RC_M; m++) {")
        a("            int64_t p = ((int64_t)rc_eq[m] << RC_SM_PF) / sm_sum;")
        a("            if (p > RC_QMAX) p = RC_QMAX;")
        a("            Y[t*RC_M + m] = (rc_storage_t)p;")
        a("        }")
    a("    }")
    a("}")
    a("")
    return "\n".join(L)


def _accum_bits(qmodel, is_structured, chain_weight_q, chain_feedback_q):
    """Pick i32 (32) or i64 (64) accumulator widths for the reservoir matmul
    and the readout, choosing i32 only when the worst-case magnitude provably
    fits a signed i32 with margin. i32 is exact-equal to i64 in that range, so
    bit-exactness with the Python/JIT reference is preserved."""
    cfg = qmodel.config
    rc = qmodel.rc
    sb = qmodel.storage_bits
    zp_state = abs(cfg.state.zero_point)
    MARGIN = 1 << 30                 # leave a bit of headroom under 2^31
    hmag = 1 << sb                   # bound on |h_q - zp_state|

    # --- reservoir ---
    if sb != 8:
        res_bits = 64
    elif is_structured:
        # at most two chain terms per row
        res_max = (abs(chain_weight_q) + abs(chain_feedback_q)) * hmag
        res_bits = 32 if res_max < MARGIN else 64
    else:
        row_abs = int(np.abs(qmodel.W_res_q.astype(np.int64)).sum(axis=1).max())
        rs_abs = int(np.abs(qmodel.row_sum_W_res).max())
        res_max = row_abs * hmag + zp_state * rs_abs
        res_bits = 32 if res_max < MARGIN else 64

    # --- readout (state block dominates) ---
    if sb != 8:
        ro_bits = 64
    else:
        K, N = qmodel.K, qmodel.N
        off = 1 if rc.readout.include_bias else 0
        if rc.readout.include_input:
            off += K
        Wstate = qmodel.W_out_q[:, off:off + N].astype(np.int64)
        row_abs = int(np.abs(Wstate).sum(axis=1).max())
        rs_abs = int(np.abs(qmodel.row_sum_Wout_state).max())
        ro_max = row_abs * hmag + zp_state * rs_abs
        ro_bits = 32 if ro_max < MARGIN else 64
    return res_bits, ro_bits


def _emit_chain_c(a, topo, N, cw_q, cf_q, zp_state, rd_s, res_t, cast):
    """Emit the structured-topology W_res contribution into `acc_res`."""
    a(f"            {res_t} acc_res = 0;")
    if topo == "SCR":
        a(f"            {{ int32_t ip = (i == 0) ? {N - 1} : (i - 1);")
        a(f"              acc_res = {cast}{cw_q} * {cast}((int32_t)rc_h[ip] - {zp_state}); }}")
    elif topo == "DLR":
        a("            if (i > 0)")
        a(f"                acc_res = {cast}{cw_q} * {cast}((int32_t)rc_h[i-1] - {zp_state});")
    elif topo == "DLRB":
        a("            if (i > 0)")
        a(f"                acc_res += {cast}{cw_q} * {cast}((int32_t)rc_h[i-1] - {zp_state});")
        a("            if (i < RC_N - 1)")
        a(f"                acc_res += {cast}{cf_q} * {cast}((int32_t)rc_h[i+1] - {zp_state});")
    else:
        raise ValueError(f"_emit_chain_c: unexpected topology {topo}")
