"""Portable-C emitter for the affine quantized reservoir kernel.

Produces a single self-contained `.c` source that implements `rc_predict`
with the exact integer arithmetic of `AffineQuantizedExecutor` /
`_AffineLowerer`, so the C kernel is bit-exact with the Python reference
and the host JIT.

Design goals:
  * **Portable.** Compiles with any C99 compiler. On AVR (`__AVR__`) the
    weight/LUT tables live in Flash via `PROGMEM` and are read with
    `pgm_read_*`; on the host they are plain arrays, so the same source
    can be compiled with host gcc and checked bit-for-bit.
  * **Small SRAM.** Only the reservoir state and pre buffers (and a tiny
    u_pre scratch) live in RAM — `2*N + K` bytes for an i8 model. Weights
    stay in Flash. A structured-topology (SCR/DLR/DLRB) i8 model fits an
    Arduino Uno (2 KB SRAM) comfortably.

Supported (mirrors the LLVM affine path):
  * storage i8 / i16, mixed-precision i16 W_out
  * topologies: SCR / DLR / DLRB (scalar chain) and dense (W_res matmul)
  * LUT strategies: direct / linear_interp / polynomial
  * integer input preprocess (input_offset / input_scaling != 0/1)
  * include_bias / include_input readout blocks
"""
from __future__ import annotations
from typing import List

import numpy as np

from rclite.core.profile import Topology
from rclite.quant.affine.quantize import AffineQuantizedModel
from rclite.quant.affine.lut import LUTKind


_C_TYPE = {8: "int8_t", 16: "int16_t", 32: "int32_t"}
_RD = {8: "RC_RD8", 16: "RC_RD16", 32: "RC_RD32"}


def _arr(name: str, ctype: str, values, rd_macro: str) -> str:
    """Emit a PROGMEM const array declaration."""
    body = ", ".join(str(int(v)) for v in np.asarray(values).reshape(-1))
    return f"static const {ctype} {name}[] RC_PROGMEM = {{ {body} }};"


def emit_affine_kernel_c(qmodel: AffineQuantizedModel,
                          fn_name: str = "rc_predict") -> str:
    rc = qmodel.rc
    cfg = qmodel.config
    sb = qmodel.storage_bits
    wob = qmodel.w_out_storage_bits
    storage_t = _C_TYPE[sb]
    wout_t = _C_TYPE[wob]
    rd_s = _RD[sb]
    rd_w = _RD[wob]

    N, K, M, F = qmodel.N, qmodel.K, qmodel.M, qmodel.F
    qmin = -(1 << (sb - 1))
    qmax = (1 << (sb - 1)) - 1

    is_structured = rc.reservoir.topology in (
        Topology.DLR, Topology.DLRB, Topology.SCR)
    topo = rc.reservoir.topology.name

    # Chain constants (match ir_builder)
    wqmin, wqmax = -(1 << (wob - 1)), (1 << (wob - 1)) - 1

    def _qw(v):
        return max(wqmin, min(wqmax, int(round(v / cfg.W_out_state.scale))))

    # chain weights are quantized at the W_res (i8) scale, not W_out
    rqmin, rqmax = -(1 << (sb - 1)), (1 << (sb - 1)) - 1

    def _qchain(v):
        return max(rqmin, min(rqmax, int(round(v / cfg.W_res.scale))))

    chain_weight_q = _qchain(float(rc.reservoir.chain_weight))
    chain_feedback_q = _qchain(float(rc.reservoir.chain_feedback))

    art = qmodel.lut_artifacts
    strat = qmodel.lut_strategy

    L: List[str] = []
    a = L.append

    # ---- header ----
    a("/* Auto-generated by rclite — affine quantized reservoir kernel. */")
    a("/* Portable C99. On AVR, tables live in Flash (PROGMEM). */")
    a("#include <stdint.h>")
    a("#ifdef __AVR__")
    a("#include <avr/pgmspace.h>")
    a("#define RC_PROGMEM PROGMEM")
    a("#define RC_RD8(p)  ((int8_t)pgm_read_byte(p))")
    a("#define RC_RD16(p) ((int16_t)pgm_read_word(p))")
    a("#define RC_RD32(p) ((int32_t)pgm_read_dword(p))")
    a("#else")
    a("#define RC_PROGMEM")
    a("#define RC_RD8(p)  (*(p))")
    a("#define RC_RD16(p) (*(p))")
    a("#define RC_RD32(p) (*(p))")
    a("#endif")
    a("")
    a(f"#define RC_N {N}")
    a(f"#define RC_K {K}")
    a(f"#define RC_M {M}")
    a(f"#define RC_F {F}")
    a(f"#define RC_QMIN ({qmin})")
    a(f"#define RC_QMAX ({qmax})")
    a("typedef %s rc_storage_t;" % storage_t)
    a("")

    # ---- weight / LUT tables ----
    a(_arr("rc_W_in", storage_t, qmodel.W_in_q, rd_s))
    a(_arr("rc_W_out", wout_t, qmodel.W_out_q, rd_w))
    a(_arr("rc_row_sum_W_in", "int32_t", qmodel.row_sum_W_in, "RC_RD32"))
    a(_arr("rc_row_sum_Wout_state", "int32_t",
            qmodel.row_sum_Wout_state, "RC_RD32"))
    if rc.readout.include_input:
        a(_arr("rc_row_sum_Wout_input", "int32_t",
                qmodel.row_sum_Wout_input, "RC_RD32"))
    if not is_structured:
        a(_arr("rc_W_res", storage_t, qmodel.W_res_q, rd_s))
        a(_arr("rc_row_sum_W_res", "int32_t", qmodel.row_sum_W_res, "RC_RD32"))
    if strat.kind in (LUTKind.DIRECT, LUTKind.LINEAR_INTERP):
        a(_arr("rc_lut", storage_t, qmodel.lut_q, rd_s))
    a("")

    # ---- SRAM state buffers ----
    a("static rc_storage_t rc_h[RC_N];")
    a("static rc_storage_t rc_pre[RC_N];")
    if qmodel.has_integer_preprocess:
        a("static rc_storage_t rc_u[RC_K];")
    a("")

    # ---- helpers ----
    a("static int32_t rc_rq(int32_t x, int32_t M0, uint8_t n){")
    a("    int64_t p = (int64_t)x * (int64_t)M0;")
    a("    if (n) p += ((int64_t)1 << (n - 1));")
    a("    return (int32_t)(p >> n);")
    a("}")
    a("static int32_t rc_clamp32(int64_t v){")
    a("    if (v < (int64_t)(-2147483647-1)) return (-2147483647-1);")
    a("    if (v > (int64_t)2147483647) return 2147483647;")
    a("    return (int32_t)v;")
    a("}")
    a("static rc_storage_t rc_sat(int32_t v){")
    a("    if (v < RC_QMIN) v = RC_QMIN;")
    a("    if (v > RC_QMAX) v = RC_QMAX;")
    a("    return (rc_storage_t)v;")
    a("}")
    a("")

    # ---- activation ----
    a("static rc_storage_t rc_activate(int32_t pre){")
    if strat.kind == LUTKind.DIRECT:
        a(f"    int32_t idx = pre + {qmodel.lut_offset};")
        a(f"    return ({storage_t}){rd_s}(&rc_lut[idx]);")
    elif strat.kind == LUTKind.LINEAR_INTERP:
        f = strat.interp_frac_bits
        n = strat.n_entries
        a(f"    int32_t norm = pre + {qmodel.lut_offset};")
        a(f"    int32_t tq = rc_rq(norm, {art.idx_M0}, {art.idx_n});")
        a(f"    int32_t idx = tq >> {f};")
        a(f"    if (idx < 0) idx = 0; if (idx > {n - 2}) idx = {n - 2};")
        a(f"    int32_t frac = tq - (idx << {f});")
        a(f"    int32_t y0 = {rd_s}(&rc_lut[idx]);")
        a(f"    int32_t y1 = {rd_s}(&rc_lut[idx + 1]);")
        a(f"    int32_t v = y0 + (((y1 - y0) * frac) >> {f});")
        a("    return rc_sat(v);")
    elif strat.kind == LUTKind.POLYNOMIAL:
        qf = strat.poly_qf_bits
        a(f"    int32_t cx = pre - {cfg.pre.zero_point};")
        a(f"    int64_t x = (int64_t)rc_rq(cx, {art.x_to_qf_M0}, {art.x_to_qf_n});")
        a(f"    if (x < {-art.x_clip_qf}) x = {-art.x_clip_qf};")
        a(f"    if (x > {art.x_clip_qf}) x = {art.x_clip_qf};")
        a(f"    int64_t x2 = (x * x) >> {qf};")
        a(f"    int64_t inner = ((x2 * {art.poly_a5_qf}) >> {qf}) + {art.poly_a3_qf};")
        a(f"    int64_t outer = ((x2 * inner) >> {qf}) + {art.poly_a1_qf};")
        a(f"    int64_t y = (x * outer) >> {qf};")
        a(f"    if (y < {-art.one_qf}) y = {-art.one_qf};")
        a(f"    if (y > {art.one_qf}) y = {art.one_qf};")
        a(f"    int32_t d = rc_rq((int32_t)y, {art.qf_to_state_M0}, {art.qf_to_state_n});")
        a(f"    return rc_sat(d + {cfg.state.zero_point});")
    a("}")
    a("")

    # ---- kernel ----
    zp_upre = cfg.u_pre.zero_point
    zp_state = cfg.state.zero_point
    zp_pre = cfg.pre.zero_point
    zp_input = cfg.input.zero_point
    zp_output = cfg.output.zero_point

    a(f"void {fn_name}(int32_t T, const rc_storage_t *X, rc_storage_t *Y){{")
    a("    int32_t t, i, j, k, m;")
    a(f"    for (i = 0; i < RC_N; i++) rc_h[i] = {zp_state};")
    a("    for (t = 0; t < T; t++) {")

    # preprocess
    if qmodel.has_integer_preprocess:
        a("        for (k = 0; k < RC_K; k++) {")
        a(f"            int32_t cx = (int32_t)X[t*RC_K + k] - {zp_input};")
        a(f"            int32_t up = rc_rq(cx, {qmodel.pre_M0}, {qmodel.pre_n}) + {qmodel.pre_const};")
        a("            rc_u[k] = rc_sat(up);")
        a("        }")
        u_expr = "rc_u[k]"
    else:
        u_expr = "X[t*RC_K + k]"

    # reservoir pre-activation
    a("        for (i = 0; i < RC_N; i++) {")
    a("            int32_t acc_in = 0;")
    a("            for (k = 0; k < RC_K; k++)")
    a(f"                acc_in += (int32_t){rd_s}(&rc_W_in[i*RC_K + k]) * (int32_t)({u_expr});")
    a(f"            acc_in -= {zp_upre} * RC_RD32(&rc_row_sum_W_in[i]);")
    a(f"            int32_t rq_in = rc_rq(rc_clamp32(acc_in), {qmodel.M_in_M0}, {qmodel.M_in_n});")
    # W_res contribution
    if is_structured:
        _emit_chain_c(a, topo, N, chain_weight_q, chain_feedback_q, zp_state, rd_s)
    else:
        a("            int64_t acc_res = 0;")
        a("            for (j = 0; j < RC_N; j++)")
        a(f"                acc_res += (int64_t){rd_s}(&rc_W_res[i*RC_N + j]) * (int64_t)rc_h[j];")
        a(f"            acc_res -= (int64_t){zp_state} * (int64_t)RC_RD32(&rc_row_sum_W_res[i]);")
    a(f"            int32_t rq_res = rc_rq(rc_clamp32(acc_res), {qmodel.M_res_M0}, {qmodel.M_res_n});")
    a(f"            rc_pre[i] = rc_sat({zp_pre + qmodel.bias_pre} + rq_in + rq_res);")
    a("        }")

    # activation + leaky integration
    a("        for (i = 0; i < RC_N; i++) {")
    a("            int32_t act = rc_activate((int32_t)rc_pre[i]);")
    a(f"            int32_t hc = (int32_t)rc_h[i] - {zp_state};")
    a(f"            int32_t ac = act - {zp_state};")
    a(f"            int32_t d = rc_rq(ac - hc, {qmodel.leak_M0}, {qmodel.leak_n});")
    a(f"            rc_h[i] = rc_sat({zp_state} + hc + d);")
    a("        }")

    # readout
    off_bias = 0
    off_input = 1 if rc.readout.include_bias else 0
    off_state = off_input + (K if rc.readout.include_input else 0)
    a("        for (m = 0; m < RC_M; m++) {")
    a(f"            int32_t y = {zp_output};")
    if rc.readout.include_bias:
        a(f"            y += rc_rq(rc_clamp32((int64_t){rd_w}(&rc_W_out[m*RC_F + {off_bias}])), "
          f"{qmodel.M_out_bias_M0}, {qmodel.M_out_bias_n});")
    if rc.readout.include_input:
        a("            int64_t acc_i = 0;")
        a("            for (k = 0; k < RC_K; k++)")
        a(f"                acc_i += (int64_t){rd_w}(&rc_W_out[m*RC_F + {off_input} + k]) "
          f"* (int64_t)X[t*RC_K + k];")
        a(f"            acc_i -= (int64_t){zp_input} * (int64_t)RC_RD32(&rc_row_sum_Wout_input[m]);")
        a(f"            y += rc_rq(rc_clamp32(acc_i), {qmodel.M_out_input_M0}, {qmodel.M_out_input_n});")
    a("            int64_t acc_s = 0;")
    a("            for (j = 0; j < RC_N; j++)")
    a(f"                acc_s += (int64_t){rd_w}(&rc_W_out[m*RC_F + {off_state} + j]) "
      f"* (int64_t)rc_h[j];")
    a(f"            acc_s -= (int64_t){zp_state} * (int64_t)RC_RD32(&rc_row_sum_Wout_state[m]);")
    a(f"            y += rc_rq(rc_clamp32(acc_s), {qmodel.M_out_state_M0}, {qmodel.M_out_state_n});")
    a("            Y[t*RC_M + m] = rc_sat(y);")
    a("        }")
    a("    }")
    a("}")
    a("")
    return "\n".join(L)


def _emit_chain_c(a, topo, N, cw_q, cf_q, zp_state, rd_s):
    """Emit the structured-topology W_res contribution into `acc_res` (int64)."""
    a("            int64_t acc_res = 0;")
    if topo == "SCR":
        a(f"            {{ int32_t ip = (i == 0) ? {N - 1} : (i - 1);")
        a(f"              acc_res = (int64_t){cw_q} * ((int32_t)rc_h[ip] - {zp_state}); }}")
    elif topo == "DLR":
        a("            if (i > 0)")
        a(f"                acc_res = (int64_t){cw_q} * ((int32_t)rc_h[i-1] - {zp_state});")
    elif topo == "DLRB":
        a("            if (i > 0)")
        a(f"                acc_res += (int64_t){cw_q} * ((int32_t)rc_h[i-1] - {zp_state});")
        a("            if (i < RC_N - 1)")
        a(f"                acc_res += (int64_t){cf_q} * ((int32_t)rc_h[i+1] - {zp_state});")
    else:
        raise ValueError(f"_emit_chain_c: unexpected topology {topo}")
