"""Portable C header (`rc_model.h`) for an emitted kernel.

Declares `rc_predict`, the model dimensions, the storage type, and inline
float<->quantized helpers so host/desktop callers can feed float data.
The kernel `.c` itself stays pure-integer; these helpers are header-only
and optional (skip them on a no-FPU target and quantize off-device).
"""

from __future__ import annotations

from .info import KernelInfo


def emit_c_header(info: KernelInfo) -> str:
    g = "RC_MODEL_H"
    L = []
    a = L.append
    a(
        f"/* Auto-generated by rclite — portable model header ({info.quant}). */"
    )
    a(f"#ifndef {g}")
    a(f"#define {g}")
    a("")
    a("#include <stdint.h>")
    a("")
    a(f"#define RC_INPUT_DIM   {info.K}")
    a(f"#define RC_OUTPUT_DIM  {info.M}")
    a(f"#define RC_RES_UNITS   {info.N}")
    a(f"#define RC_STORAGE_BITS {info.storage_bits}")
    a(f"#define RC_NUM_CLASSES {info.n_classes}")
    a(
        f"/* topology: {info.topology}, quantization: {info.quant}, "
        f"task: {info.task}, head: {info.head} */"
    )
    a("")
    a(f"typedef {info.storage_ctype} rc_storage_t;")
    if info.is_proba:
        a(
            f"/* probabilities are emitted at Q.{info.prob_frac} "
            f"(divide by {1 << info.prob_frac} for float). */"
        )
        a(f"#define RC_PROB_FRAC {info.prob_frac}")
    a("")
    a("/* Affine (scale, zero_point) view of the I/O tensors:")
    a(" *   quantize(x)   = round(x / RC_IN_SCALE)  + RC_IN_ZP   (saturated)")
    a(" *   dequantize(q) = (q - RC_OUT_ZP) * RC_OUT_SCALE")
    a(" */")
    a(f"#define RC_IN_SCALE   ({info.in_scale:.9g}f)")
    a(f"#define RC_IN_ZP      ({info.in_zp})")
    a(f"#define RC_OUT_SCALE  ({info.out_scale:.9g}f)")
    a(f"#define RC_OUT_ZP     ({info.out_zp})")
    a(f"#define RC_Q_MIN      ({info.qmin})")
    a(f"#define RC_Q_MAX      ({info.qmax})")
    a("")
    a("#ifdef __cplusplus")
    a('extern "C" {')
    a("#endif")
    a("")
    a("/* Run inference over a length-T sequence (pure integer, no libm).")
    a(" *   X: row-major (T x RC_INPUT_DIM)  quantized input,  caller-owned")
    if info.is_classify:
        a(
            " *   Y: (T,) int32 class ids (argmax of the readout), caller-allocated"
        )
    elif info.is_proba:
        a(
            " *   Y: row-major (T x RC_OUTPUT_DIM) probabilities at Q.RC_PROB_FRAC"
        )
    else:
        a(
            " *   Y: row-major (T x RC_OUTPUT_DIM) quantized output, caller-allocated"
        )
    a(" * State is reset at entry; each call is an independent run. */")
    a(
        f"void rc_predict(int32_t T, const rc_storage_t *X, {info.out_ctype} *Y);"
    )
    a("")
    a("/* Optional float helpers (host/desktop). Require floating point. */")
    a("#ifndef RC_NO_FLOAT")
    a("static inline rc_storage_t rc_quantize_input(float v){")
    a(
        "    long q = (long)(v / RC_IN_SCALE + (v >= 0 ? 0.5f : -0.5f)) + RC_IN_ZP;"
    )
    a("    if (q < RC_Q_MIN) q = RC_Q_MIN;")
    a("    if (q > RC_Q_MAX) q = RC_Q_MAX;")
    a("    return (rc_storage_t)q;")
    a("}")
    if info.is_proba:
        a("static inline float rc_dequantize_output(rc_storage_t q){")
        a("    return (float)q / (float)(1 << RC_PROB_FRAC);")
        a("}")
    elif not info.is_classify:
        a("static inline float rc_dequantize_output(rc_storage_t q){")
        a("    return ((float)q - (float)RC_OUT_ZP) * RC_OUT_SCALE;")
        a("}")
    a("#endif /* RC_NO_FLOAT */")
    a("")
    a("#ifdef __cplusplus")
    a("}")
    a("#endif")
    a("")
    a(f"#endif /* {g} */")
    a("")
    return "\n".join(L)
