"""Portable-C emitter for the **symmetric Q-format** quantized kernel.

Bit-exact with `rclite.quant.QuantizedExecutor` (the Python reference for
the I32/I16/I8 mirage-style path). Mirrors `_IntLowerer` in C:

  * pre-activation: per-row accumulator with two's-complement i32 wrap and
    `(W * x) >> shift` fixed-point multiplies
  * tanh via linear-interpolated LUT (mirage `tanh_lut_q`)
  * leaky integration at the state scale
  * mirage mixed-scale readout (bias / input passthrough / state blocks),
    accumulated in i64 and shifted back by `state_frac`
  * structured topologies (SCR/DLR/DLRB) use a scalar chain (the quantized
    chain weight equals the dense W_res entry, so this matches the
    executor's sparse-over-dense matmul exactly); dense otherwise

Weights/LUT live in Flash via PROGMEM on AVR. The truncation/wrap uses
unsigned arithmetic so it is well-defined C (no signed-overflow UB) while
reproducing numpy's `trunc_i32` / `astype` wrap behaviour.
"""
from __future__ import annotations
from typing import List

import numpy as np

from rclite.core.profile import Topology
from rclite.quant.model import QuantizedModel


_C_TYPE = {8: "int8_t", 16: "int16_t", 32: "int32_t"}
_RD = {8: "RC_RD8", 16: "RC_RD16", 32: "RC_RD32"}


def _arr(name: str, ctype: str, values) -> str:
    body = ", ".join(str(int(v)) for v in np.asarray(values).reshape(-1))
    return f"static const {ctype} {name}[] RC_PROGMEM = {{ {body} }};"


def _sat_storage(v: int, sb: int) -> int:
    lo, hi = -(1 << (sb - 1)), (1 << (sb - 1)) - 1
    return max(lo, min(hi, int(v)))


def emit_symmetric_kernel_c(qmodel: QuantizedModel,
                             fn_name: str = "rc_predict") -> str:
    rc = qmodel.rc
    cfg = qmodel.config
    sb = qmodel.target.storage_bits
    storage_t = _C_TYPE[sb]
    rd = _RD[sb]
    N, K, M = qmodel.N, qmodel.K, qmodel.M
    F = qmodel.F
    qmin, qmax = -(1 << (sb - 1)), (1 << (sb - 1)) - 1

    state_frac = cfg.state_frac
    input_frac = cfg.input_frac
    weight_frac = cfg.weight_frac
    shift_in = weight_frac + input_frac - state_frac
    if shift_in < 0:
        raise NotImplementedError(
            f"symmetric C emit needs weight_frac+input_frac >= state_frac "
            f"(shift_in={shift_in})")
    shift_res = weight_frac
    state_scale = 1 << state_frac
    input_scale = 1 << input_frac
    weight_scale = 1 << weight_frac

    # bias/leak follow `QuantTarget.quantize_state`: int(x * scale) (truncate
    # toward zero), then saturate to storage. NOT round() — the executor uses
    # plain int() here, and rounding would diverge by one LSB.
    bias_q = _sat_storage(int(float(rc.reservoir.bias) * state_scale), sb)
    leak_q = _sat_storage(int(float(rc.reservoir.leak_rate) * state_scale), sb)
    one_minus_leak_q = state_scale - leak_q
    xmin_q = int(qmodel.lut.xmin * state_scale)
    xmax_q = int(qmodel.lut.xmax * state_scale)
    denom = xmax_q - xmin_q
    lut_n = int(np.asarray(qmodel.lut_table_q).shape[0])

    offset_q = int(round(float(rc.input.input_offset) * input_scale))
    scaling_q = int(round(float(rc.input.input_scaling) * weight_scale))

    is_structured = rc.reservoir.topology in (
        Topology.DLR, Topology.DLRB, Topology.SCR)
    topo = rc.reservoir.topology.name

    # Chain weights are read straight from the quantized dense W_res so they
    # are byte-identical to what the executor's CSR-over-dense matmul reads.
    # Structured topologies place the forward chain on the lower sub-diagonal
    # (W_res_q[i, i-1]) and the DLRB feedback on the upper one (W_res_q[i, i+1]);
    # all forward (resp. backward) entries share one scalar, so a single
    # representative entry is exact.
    Wr = np.asarray(qmodel.W_res_q)
    chain_weight_q = int(Wr[1, 0]) if (is_structured and N > 1) else 0
    chain_feedback_q = int(Wr[0, 1]) if (is_structured and N > 1) else 0

    off_bias = 0
    off_input = 1 if rc.readout.include_bias else 0
    off_state = off_input + (K if rc.readout.include_input else 0)

    L: List[str] = []
    a = L.append

    a("/* Auto-generated by rclite — symmetric Q-format reservoir kernel. */")
    a("/* Portable C99. On AVR, tables live in Flash (PROGMEM). */")
    a("#include <stdint.h>")
    a("#ifdef __AVR__")
    a("#include <avr/pgmspace.h>")
    a("#define RC_PROGMEM PROGMEM")
    a("#define RC_RD8(p)  ((int8_t)pgm_read_byte(p))")
    a("#define RC_RD16(p) ((int16_t)pgm_read_word(p))")
    a("#define RC_RD32(p) ((int32_t)pgm_read_dword(p))")
    a("#else")
    a("#define RC_PROGMEM")
    a("#define RC_RD8(p)  (*(p))")
    a("#define RC_RD16(p) (*(p))")
    a("#define RC_RD32(p) (*(p))")
    a("#endif")
    a("")
    a(f"#define RC_N {N}")
    a(f"#define RC_K {K}")
    a(f"#define RC_M {M}")
    a(f"#define RC_F {F}")
    a(f"#define RC_QMIN ({qmin})")
    a(f"#define RC_QMAX ({qmax})")
    a(f"#define RC_STATE_FRAC {state_frac}")
    a(f"#define RC_SHIFT_IN {shift_in}")
    a(f"#define RC_SHIFT_RES {shift_res}")
    a(f"typedef {storage_t} rc_storage_t;")
    a("")

    # tables
    a(_arr("rc_W_in", storage_t, qmodel.W_in_q))
    a(_arr("rc_W_out", storage_t, qmodel.W_out_q))
    a(_arr("rc_lut", storage_t, qmodel.lut_table_q))
    if not is_structured:
        a(_arr("rc_W_res", storage_t, qmodel.W_res_q))
    a("")
    a("static rc_storage_t rc_h[RC_N];")
    a("static rc_storage_t rc_pre[RC_N];")
    a("static rc_storage_t rc_u[RC_K];")
    a("")

    # helpers: two's-complement wrap (well-defined via unsigned)
    a("static int32_t rc_w32(int64_t v){ return (int32_t)(uint32_t)(uint64_t)v; }")
    a(f"static rc_storage_t rc_ws(int32_t v){{ return ({storage_t})v; }}")
    a("static int32_t rc_fmul(int32_t a, int32_t b, int s){")
    a("    return rc_w32(((int64_t)a * (int64_t)b) >> s);")
    a("}")
    a("")

    # tanh LUT (linear interp), mirage tanh_lut_q
    a("static rc_storage_t rc_tanh(int32_t x){")
    a(f"    if (x < {xmin_q}) x = {xmin_q};")
    a(f"    if (x > {xmax_q}) x = {xmax_q};")
    a(f"    int64_t num = (int64_t)x - ({xmin_q});")
    a(f"    int32_t tq = rc_w32((num << RC_STATE_FRAC) / ({denom}));")
    a(f"    int32_t pos = rc_w32((int64_t)tq * ({lut_n - 1}));")
    a("    int32_t i0 = pos >> RC_STATE_FRAC;")
    a(f"    if (i0 < 0) i0 = 0; if (i0 > {lut_n - 2}) i0 = {lut_n - 2};")
    a("    int32_t frac = pos - rc_w32((int64_t)i0 << RC_STATE_FRAC);")
    a(f"    int32_t y0 = {rd}(&rc_lut[i0]);")
    a(f"    int32_t y1 = {rd}(&rc_lut[i0 + 1]);")
    a("    int32_t interp = rc_w32((int64_t)y0 + (((int64_t)(y1 - y0) * frac) >> RC_STATE_FRAC));")
    a("    return rc_ws(interp);")
    a("}")
    a("")

    # kernel
    a(f"void {fn_name}(int32_t T, const rc_storage_t *X, rc_storage_t *Y){{")
    a("    int32_t t, i, j, k, m;")
    a("    for (i = 0; i < RC_N; i++) rc_h[i] = 0;")
    a("    for (t = 0; t < T; t++) {")
    # preprocess: u_pre[k] = wrap_s( ((X - offset_q) * scaling_q) >> weight_frac )
    a("        for (k = 0; k < RC_K; k++) {")
    a(f"            int64_t d = (int64_t)X[t*RC_K + k] - ({offset_q});")
    a(f"            rc_u[k] = rc_ws(rc_w32((d * ({scaling_q})) >> {weight_frac}));")
    a("        }")
    # pre-activation
    a("        for (i = 0; i < RC_N; i++) {")
    a(f"            int32_t acc = {bias_q};")
    a("            for (k = 0; k < RC_K; k++)")
    a(f"                acc = rc_w32((int64_t)acc + rc_fmul({rd}(&rc_W_in[i*RC_K + k]), rc_u[k], RC_SHIFT_IN));")
    if is_structured:
        _emit_chain_sym(a, topo, N, chain_weight_q, chain_feedback_q, rd)
    else:
        a("            for (j = 0; j < RC_N; j++)")
        a(f"                acc = rc_w32((int64_t)acc + rc_fmul({rd}(&rc_W_res[i*RC_N + j]), rc_h[j], RC_SHIFT_RES));")
    a("            rc_pre[i] = rc_ws(acc);")
    a("        }")
    # activation + leaky integration
    a("        for (i = 0; i < RC_N; i++) {")
    a("            rc_storage_t act = rc_tanh((int32_t)rc_pre[i]);")
    a(f"            rc_storage_t t1 = rc_ws(rc_fmul(rc_h[i], {one_minus_leak_q}, RC_STATE_FRAC));")
    a(f"            rc_storage_t t2 = rc_ws(rc_fmul(act, {leak_q}, RC_STATE_FRAC));")
    a("            rc_h[i] = rc_ws((int32_t)t1 + (int32_t)t2);")
    a("        }")
    # readout (mirage mixed-scale, i64 accumulate)
    a("        for (m = 0; m < RC_M; m++) {")
    a("            int64_t out = 0;")
    if rc.readout.include_bias:
        a(f"            out += ((int64_t)1 << RC_STATE_FRAC) * (int64_t){rd}(&rc_W_out[m*RC_F + {off_bias}]);")
    if rc.readout.include_input:
        a("            for (k = 0; k < RC_K; k++)")
        a(f"                out += (int64_t){rd}(&rc_W_out[m*RC_F + {off_input} + k]) * (int64_t)X[t*RC_K + k];")
    a("            for (j = 0; j < RC_N; j++)")
    a(f"                out += (int64_t){rd}(&rc_W_out[m*RC_F + {off_state} + j]) * (int64_t)rc_h[j];")
    a("            int64_t sh = out >> RC_STATE_FRAC;")
    a("            if (sh < RC_QMIN) sh = RC_QMIN;")
    a("            if (sh > RC_QMAX) sh = RC_QMAX;")
    a("            Y[t*RC_M + m] = (rc_storage_t)sh;")
    a("        }")
    a("    }")
    a("}")
    a("")
    return "\n".join(L)


def _emit_chain_sym(a, topo, N, cw_q, cf_q, rd):
    """Structured-topology W_res contribution, matching the dense-CSR matmul."""
    if topo == "SCR":
        a(f"            {{ int32_t ip = (i == 0) ? {N - 1} : (i - 1);")
        a(f"              acc = rc_w32((int64_t)acc + rc_fmul({cw_q}, rc_h[ip], RC_SHIFT_RES)); }}")
    elif topo == "DLR":
        a("            if (i > 0)")
        a(f"                acc = rc_w32((int64_t)acc + rc_fmul({cw_q}, rc_h[i-1], RC_SHIFT_RES));")
    elif topo == "DLRB":
        a("            if (i > 0)")
        a(f"                acc = rc_w32((int64_t)acc + rc_fmul({cw_q}, rc_h[i-1], RC_SHIFT_RES));")
        a("            if (i < RC_N - 1)")
        a(f"                acc = rc_w32((int64_t)acc + rc_fmul({cf_q}, rc_h[i+1], RC_SHIFT_RES));")
    else:
        raise ValueError(f"_emit_chain_sym: unexpected topology {topo}")
