"""Rust wrapper crate for an emitted kernel.

The wrapper is a thin, safe FFI binding to the portable C kernel (compiled
by `build.rs` via the `cc` crate), plus model metadata constants. The core
`predict_into` is `no_std`-friendly (pure integer); float helpers that
quantize/dequantize sit behind the default `std` feature.
"""

from __future__ import annotations

from .info import KernelInfo


def emit_rust_lib(info: KernelInfo) -> str:
    s = info.storage_rust
    L = []
    a = L.append
    a("//! Auto-generated by rclite — safe Rust wrapper over the portable")
    a(
        f"//! C reservoir kernel (quantization: {info.quant}, topology: {info.topology})."
    )
    a("//!")
    a("//! `predict_into` is pure-integer and works in `no_std`. The float")
    a("//! helpers (`predict`, `quantize_input`, `dequantize_output`) are")
    a("//! behind the default `std` feature.")
    a('#![cfg_attr(not(feature = "std"), no_std)]')
    a("")
    a("/// Reservoir input dimension.")
    a(f"pub const INPUT_DIM: usize = {info.K};")
    a("/// Reservoir output dimension.")
    a(f"pub const OUTPUT_DIM: usize = {info.M};")
    a("/// Reservoir units.")
    a(f"pub const RES_UNITS: usize = {info.N};")
    a("/// Quantized storage element type.")
    a(f"pub type Storage = {s};")
    a("")
    a("/// Input quantization scale: `q = round(x / IN_SCALE) + IN_ZP`.")
    a(f"pub const IN_SCALE: f32 = {info.in_scale:.9e};")
    a(f"pub const IN_ZP: i32 = {info.in_zp};")
    a("/// Output dequantization: `y = (q - OUT_ZP) * OUT_SCALE`.")
    a(f"pub const OUT_SCALE: f32 = {info.out_scale:.9e};")
    a(f"pub const OUT_ZP: i32 = {info.out_zp};")
    a(f"const Q_MIN: i32 = {info.qmin};")
    a(f"const Q_MAX: i32 = {info.qmax};")
    if info.task == "CLASSIFICATION":
        a(
            f"/// Number of classes (= OUTPUT_DIM for a classification readout)."
        )
        a(f"pub const NUM_CLASSES: usize = {info.n_classes};")
    if info.is_proba:
        a(f"/// Probabilities are emitted at Q.{info.prob_frac}.")
        a(f"pub const PROB_FRAC: u32 = {info.prob_frac};")
    a("")
    a(f'extern "C" {{')
    a(
        f"    fn rc_predict(t: i32, x: *const Storage, y: *mut {info.out_rust});"
    )
    a("}")
    a("")
    a("/// Quantize a float input sample to storage units (saturating).")
    a('#[cfg(feature = "std")]')
    a("pub fn quantize_input(v: f32) -> Storage {")
    a("    let q = (v / IN_SCALE).round() as i32 + IN_ZP;")
    a("    q.clamp(Q_MIN, Q_MAX) as Storage")
    a("}")
    a("")

    if info.is_classify:
        a(
            "/// Run `T = x.len()/INPUT_DIM` steps and write one class id per step"
        )
        a(
            "/// (`argmax` of the readout) into `y` (length `T`). Pure integer; `no_std`."
        )
        a("pub fn classify_into(x: &[Storage], y: &mut [i32]) {")
        a(
            '    assert!(x.len() % INPUT_DIM == 0, "x length must be a multiple of INPUT_DIM");'
        )
        a("    let t = x.len() / INPUT_DIM;")
        a('    assert_eq!(y.len(), t, "y length must be T");')
        a(
            "    // SAFETY: lengths validated; the kernel reads t*K from x, writes t to y."
        )
        a("    unsafe { rc_predict(t as i32, x.as_ptr(), y.as_mut_ptr()); }")
        a("}")
        a("")
        a(
            "/// Float convenience: quantize `x`, run, and return one class id per step."
        )
        a('#[cfg(feature = "std")]')
        a("pub fn classify(x: &[f32]) -> std::vec::Vec<u32> {")
        a(
            "    let xq: std::vec::Vec<Storage> = x.iter().map(|&v| quantize_input(v)).collect();"
        )
        a("    let t = xq.len() / INPUT_DIM;")
        a("    let mut y = std::vec![0i32; t];")
        a("    classify_into(&xq, &mut y);")
        a("    y.iter().map(|&c| c as u32).collect()")
        a("}")
        a("")
        return "\n".join(L)

    # logits / proba: storage output, T x OUTPUT_DIM
    a("/// Run `T = x.len()/INPUT_DIM` steps of quantized inference, writing")
    a(
        "/// `T * OUTPUT_DIM` quantized outputs into `y`. Pure integer; `no_std`."
    )
    a("///")
    a("/// # Panics")
    a("/// If `x`/`y` lengths are not exact multiples of the I/O dims, or if")
    a("/// they disagree on the number of steps.")
    a("pub fn predict_into(x: &[Storage], y: &mut [Storage]) {")
    a(
        '    assert!(x.len() % INPUT_DIM == 0, "x length must be a multiple of INPUT_DIM");'
    )
    a("    let t = x.len() / INPUT_DIM;")
    a(
        '    assert_eq!(y.len(), t * OUTPUT_DIM, "y length must be T * OUTPUT_DIM");'
    )
    a(
        "    // SAFETY: lengths validated above; the C kernel only reads t*K from x"
    )
    a("    // and writes t*M to y, and resets its own state on entry.")
    a("    unsafe { rc_predict(t as i32, x.as_ptr(), y.as_mut_ptr()); }")
    a("}")
    a("")
    a("/// Dequantize a storage-unit output back to float.")
    a('#[cfg(feature = "std")]')
    a("pub fn dequantize_output(q: Storage) -> f32 {")
    if info.is_proba:
        a("    q as f32 / (1u32 << PROB_FRAC) as f32")
    else:
        a("    (q as f32 - OUT_ZP as f32) * OUT_SCALE")
    a("}")
    a("")
    a("/// Float convenience: quantize `x` (row-major T x INPUT_DIM), run the")
    if info.is_proba:
        a("/// kernel, and return `T x OUTPUT_DIM` class probabilities.")
    else:
        a("/// kernel, and return dequantized `T x OUTPUT_DIM` outputs.")
    a('#[cfg(feature = "std")]')
    a("pub fn predict(x: &[f32]) -> std::vec::Vec<f32> {")
    a(
        "    let xq: std::vec::Vec<Storage> = x.iter().map(|&v| quantize_input(v)).collect();"
    )
    a("    let t = xq.len() / INPUT_DIM;")
    a("    let mut yq = std::vec![0 as Storage; t * OUTPUT_DIM];")
    a("    predict_into(&xq, &mut yq);")
    a("    yq.iter().map(|&q| dequantize_output(q)).collect()")
    a("}")
    a("")
    return "\n".join(L)


def emit_cargo_toml(info: KernelInfo) -> str:
    crate = info.name.replace("-", "_")
    return "\n".join(
        [
            "# Auto-generated by rclite.",
            "[package]",
            f'name = "{crate}"',
            'version = "0.1.0"',
            'edition = "2021"',
            "",
            "[features]",
            'default = ["std"]',
            "std = []",
            "",
            "[build-dependencies]",
            'cc = "1"',
            "",
            "[lib]",
            'crate-type = ["rlib", "staticlib"]',
            "",
        ]
    )


def emit_build_rs(info: KernelInfo) -> str:
    return "\n".join(
        [
            "// Auto-generated by rclite — compiles the portable C kernel.",
            "fn main() {",
            '    println!("cargo:rerun-if-changed=rc_kernel.c");',
            '    println!("cargo:rerun-if-changed=rc_model.h");',
            "    cc::Build::new()",
            '        .file("rc_kernel.c")',
            "        .opt_level(2)",
            '        .compile("rc_kernel");',
            "}",
            "",
        ]
    )
