/* GBA Echo State Network demo — Mackey-Glass one-step prediction.
 *
 * Mirrors the reference esn-on-gba: Mode 3 (240x160, 16bpp bitmap), plots the
 * ground-truth series in green and the ESN's one-step prediction in red, with
 * text labels. The reservoir kernel (rc_predict) is generated by rclite's GBA
 * target and linked in; the trained weights and the eval series live in the
 * generated headers.
 *
 * After rendering, the framebuffer is streamed out over mGBA's debug log
 * (2 bits/pixel, 4-colour palette) so the host build script can reconstruct
 * a PNG of exactly what the GBA drew — a faithful "screenshot" without needing
 * the emulator's video output.
 */
#include <stdint.h>
#include "esn_data.h" /* EVAL_STEPS, EVAL_U_Q[] (i16), EVAL_TRUTH[] (f32),
                              OUT_SCALE, OUT_ZP */
#include "mgba_log.h"

/* rclite's affine-i16 kernel: Y_q[t] = ESN(X_q[t]) at the model's output
 * scale; integer math + LUT tanh (no soft-float). State reset at call start. */
extern void rc_predict(int64_t T, int16_t *X, int16_t *Y);

#define SCREEN_W 240
#define SCREEN_H 160
static volatile uint16_t *const VRAM = (volatile uint16_t *)0x06000000;

#define COL_BLACK 0x0000
#define COL_WHITE 0x7FFF
#define COL_GREEN 0x03E0 /* BGR555: g=31 */
#define COL_RED 0x001F   /* BGR555: r=31 */

static void put_pixel(int x, int y, uint16_t c)
{
    if ((unsigned)x < SCREEN_W && (unsigned)y < SCREEN_H)
        VRAM[y * SCREEN_W + x] = c;
}

static void clear_screen(uint16_t c)
{
    for (int i = 0; i < SCREEN_W * SCREEN_H; i++)
        VRAM[i] = c;
}

/* ------------------------------------------------------------------ font */
/* 8x8 glyphs (digits + A-Z + space), ported from the reference utils.rs. */
static const uint8_t DIGITS[10][8] = {
    {0x3C, 0x66, 0x6E, 0x76, 0x66, 0x66, 0x3C, 0x00},
    {0x18, 0x38, 0x18, 0x18, 0x18, 0x18, 0x7E, 0x00},
    {0x3C, 0x66, 0x06, 0x0C, 0x30, 0x60, 0x7E, 0x00},
    {0x3C, 0x66, 0x06, 0x1C, 0x06, 0x66, 0x3C, 0x00},
    {0x0C, 0x1C, 0x3C, 0x6C, 0x7E, 0x0C, 0x1E, 0x00},
    {0x7E, 0x60, 0x7C, 0x06, 0x06, 0x66, 0x3C, 0x00},
    {0x1C, 0x30, 0x60, 0x7C, 0x66, 0x66, 0x3C, 0x00},
    {0x7E, 0x06, 0x0C, 0x18, 0x30, 0x30, 0x30, 0x00},
    {0x3C, 0x66, 0x66, 0x3C, 0x66, 0x66, 0x3C, 0x00},
    {0x3C, 0x66, 0x66, 0x3E, 0x06, 0x0C, 0x38, 0x00},
};
static const uint8_t LETTERS[26][8] = {
    {0x18, 0x24, 0x42, 0x42, 0x7E, 0x42, 0x42, 0x00}, /* A */
    {0x7C, 0x42, 0x42, 0x7C, 0x42, 0x42, 0x7C, 0x00}, /* B */
    {0x3C, 0x42, 0x40, 0x40, 0x40, 0x42, 0x3C, 0x00}, /* C */
    {0x78, 0x44, 0x42, 0x42, 0x42, 0x44, 0x78, 0x00}, /* D */
    {0x7E, 0x40, 0x40, 0x7C, 0x40, 0x40, 0x7E, 0x00}, /* E */
    {0x7E, 0x40, 0x40, 0x7C, 0x40, 0x40, 0x40, 0x00}, /* F */
    {0x3C, 0x42, 0x40, 0x4E, 0x42, 0x42, 0x3C, 0x00}, /* G */
    {0x42, 0x42, 0x42, 0x7E, 0x42, 0x42, 0x42, 0x00}, /* H */
    {0x3C, 0x18, 0x18, 0x18, 0x18, 0x18, 0x3C, 0x00}, /* I */
    {0x1E, 0x08, 0x08, 0x08, 0x48, 0x48, 0x30, 0x00}, /* J */
    {0x42, 0x44, 0x48, 0x70, 0x48, 0x44, 0x42, 0x00}, /* K */
    {0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x7E, 0x00}, /* L */
    {0x42, 0x66, 0x5A, 0x42, 0x42, 0x42, 0x42, 0x00}, /* M */
    {0x42, 0x62, 0x52, 0x4A, 0x46, 0x42, 0x42, 0x00}, /* N */
    {0x3C, 0x42, 0x42, 0x42, 0x42, 0x42, 0x3C, 0x00}, /* O */
    {0x7C, 0x42, 0x42, 0x7C, 0x40, 0x40, 0x40, 0x00}, /* P */
    {0x3C, 0x42, 0x42, 0x42, 0x4A, 0x44, 0x3A, 0x00}, /* Q */
    {0x7C, 0x42, 0x42, 0x7C, 0x48, 0x44, 0x42, 0x00}, /* R */
    {0x3E, 0x40, 0x40, 0x3C, 0x02, 0x02, 0x7C, 0x00}, /* S */
    {0x7E, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x00}, /* T */
    {0x42, 0x42, 0x42, 0x42, 0x42, 0x42, 0x3C, 0x00}, /* U */
    {0x42, 0x42, 0x42, 0x24, 0x24, 0x18, 0x18, 0x00}, /* V */
    {0x42, 0x42, 0x5A, 0x5A, 0x66, 0x66, 0x42, 0x00}, /* W */
    {0x42, 0x24, 0x18, 0x18, 0x18, 0x24, 0x42, 0x00}, /* X */
    {0x42, 0x24, 0x18, 0x18, 0x18, 0x18, 0x18, 0x00}, /* Y */
    {0x7E, 0x04, 0x08, 0x18, 0x20, 0x40, 0x7E, 0x00}, /* Z */
};

static void draw_char(char ch, int x, int y, uint16_t color)
{
    const uint8_t *g = 0;
    if (ch >= '0' && ch <= '9')
        g = DIGITS[ch - '0'];
    else if (ch >= 'A' && ch <= 'Z')
        g = LETTERS[ch - 'A'];
    else if (ch == ' ')
        return;
    else
        return;
    for (int row = 0; row < 8; row++)
    {
        uint8_t bits = g[row];
        for (int col = 0; col < 8; col++)
            if (bits & (0x80 >> col))
                put_pixel(x + col, y + row, color);
    }
}

static void draw_text(const char *s, int x, int y, uint16_t color)
{
    int cx = x;
    for (; *s; s++)
    {
        draw_char(*s, cx, y, color);
        cx += 8;
    }
}

/* ------------------------------------------------------------------ main */
static int16_t Xq[EVAL_STEPS];
static int16_t Yq[EVAL_STEPS];

/* Stream the framebuffer out over the debug log as 2-bit/pixel hex so the
 * host can rebuild a PNG. 0=black 1=white 2=green 3=red. */
static int color_code(uint16_t c)
{
    if (c == COL_GREEN)
        return 2;
    if (c == COL_RED)
        return 3;
    if (c == COL_WHITE)
        return 1;
    return 0;
}
static void dump_framebuffer(void)
{
    static const char hex[] = "0123456789abcdef";
    mgba_log("FB_BEGIN");
    int total = SCREEN_W * SCREEN_H; /* 38400 px */
    int i = 0;
    while (i < total)
    {
        ln_reset();
        /* 96 pixels per line -> 24 packed bytes -> 48 hex chars */
        for (int n = 0; n < 96 && i < total; n += 4)
        {
            int b = 0;
            for (int k = 0; k < 4 && i < total; k++, i++)
                b |= color_code(VRAM[i]) << (k * 2);
            char pair[3] = {hex[(b >> 4) & 0xf], hex[b & 0xf], 0};
            ln_puts(pair);
        }
        ln_flush();
    }
    mgba_log("FB_END");
}

int main(void)
{
    /* DISPCNT: video mode 3 + show BG2 (0x0403). */
    *(volatile uint16_t *)0x04000000 = 0x0403;
    clear_screen(COL_BLACK);

    mgba_open();
    mgba_log("ESN_GBA_START");

    draw_text("MACKEY GLASS", 4, 4, COL_WHITE);
    draw_text("TRUTH", 4, 16, COL_GREEN);
    draw_text("PRED", 4, 26, COL_RED);

    /* Run the reservoir over the whole eval window (quantized i16 in/out). */
    for (int i = 0; i < EVAL_STEPS; i++)
        Xq[i] = EVAL_U_Q[i];
    rc_predict((int64_t)EVAL_STEPS, Xq, Yq);

    int steps = EVAL_STEPS < SCREEN_W ? EVAL_STEPS : SCREEN_W;

    /* Auto-scale the plot to the truth range (matches the reference). */
    float vmin = EVAL_TRUTH[0], vmax = EVAL_TRUTH[0];
    for (int i = 1; i < steps; i++)
    {
        float v = EVAL_TRUTH[i];
        if (v < vmin)
            vmin = v;
        if (v > vmax)
            vmax = v;
    }
    float range = vmax - vmin;
    if (range < 1e-6f)
        range = 1e-6f;
    float mid = (vmax + vmin) * 0.5f;
    float center_y = SCREEN_H * 0.5f;
    float scale = SCREEN_H * 0.45f / range;

    for (int i = 0; i < steps; i++)
    {
        float pred = ((float)Yq[i] - OUT_ZP) * OUT_SCALE; /* dequantize */
        int yt = (int)(center_y - (EVAL_TRUTH[i] - mid) * scale);
        int yp = (int)(center_y - (pred - mid) * scale);
        if (yt >= 0 && yt < SCREEN_H)
            put_pixel(i, yt, COL_GREEN);
        if (yp >= 0 && yp < SCREEN_H)
            put_pixel(i, yp, COL_RED);
    }

    dump_framebuffer();
    mgba_log("RENDER_DONE");

    for (;;)
    { /* image persists in VRAM; VBlank IRQ keeps the core alive */
    }
    return 0;
}
